### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by kensayo**
In this first milestone, I follow the pathwrigth, seeing videos about Entity Relationship Diagram (ERD), and Primary and Foreign Keys to make the ERD that I've added for this project.

I've been thinking about creating the next tables:

- Users.
- Friendship.
- Post.
- Likes.
- Comments.

Finally, I got the approvement by rubocop linters :)

### CODE REVIEW

**Review by cyonii — CHANGES_REQUESTED** [review]
### STATUS: CHANGES REQUIRED ♻️✍️

Hello coder,
Great start for your ERD.

#### TO IMPROVE
- [ ] You did not assign Primary Keys (PK) and Foreign Keys (FK) correctly where appropriate. Kindly assign PK or FK where necessary.
- [ ] Kindly name your entities in singular form, e.g, `Friendship`, `User`, etc
- [ ] Consider specifying the cardinality (type of relationship, e.g One-To-Many) of your associations.

> #### <br>Feel free to leave a comment or question if something is not clear.<br> Slack: @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR)<br><br>

**Comment by kensayo** [comment]
> ### STATUS: CHANGES REQUIRED ♻️✍️
> Hello coder,
> Great start for your ERD.
> 
> #### TO IMPROVE
> * [x]  You did not assign Primary Keys (PK) and Foreign Keys (FK) correctly where appropriate. Kindly assign PK or FK where necessary.
> * [x]  Kindly name your entities in singular form, e.g, `Friendship`, `User`, etc
> * [x]  Consider specifying the cardinality (type of relationship, e.g One-To-Many) of your associations.
> 
> > #### Feel free to leave a comment or question if something is not clear. Slack: @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR)

Hi, you make reference only in the diagram? or the code it self?

**Comment by cyonii** [comment]
Hello @kensayo, I’m making references to the diagram

**Review by carlos-ssh — APPROVED** [review]
Hi @kensayo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
